---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
spec:
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: ar4mirez/weatherapp:v1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: weatherapp
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapp
spec:
  selector:
    app: weatherapp
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weatherapp
  labels:
    name: weatherapp
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: weatherapp
            port: 
              number: 80
