apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: weatherapp
spec:
  podSelector:
    matchLabels:
      app: weatherapp
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}