---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: weatherapp-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: weatherapp-86-109-8-247@nip.io
    privateKeySecretRef:
      name: weatherapp-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx